const logger = require('../logger');

function isInFamily(res, code) {
    let number = res.statusCode - code;
    return number < 100 && number >= 0;
}

module.exports = (req, res, next) => {
    const oldWrite = res.write,
        oldEnd = res.end;

    const chunks = [];

    res.write = function (chunk) {
        chunks.push(chunk);

        oldWrite.apply(res, arguments);
    };

    res.end = function (chunk) {
        if (chunk)
            chunks.push(chunk);
        try {
            const body = typeof chunk === 'object' ? Buffer.concat(chunks).toString('utf8') : chunk;

            const isSuccess = isInFamily(res, 200);
            const isInternalError = isInFamily(res, 500);

            const messageType = isSuccess ? 'response' : 'error';
            const logType = isInternalError ? 'error' : (isSuccess ? 'info' : 'warn');
            // console.log(err);
            logger.log(logType, `${messageType}: ${req.path} ${res.statusCode}`, {body});

            oldEnd.apply(res, arguments);
        } catch (e) {
            logger.log('error', 'cannot resolve response');
        }
    };

    next();
};

const t = {
    "_events": {},
    "_eventsCount": 1,
    "outputData": [],
    "outputSize": 0,
    "writable": true,
    "_last": false,
    "chunkedEncoding": false,
    "shouldKeepAlive": true,
    "useChunkedEncodingByDefault": true,
    "sendDate": true,
    "_removedConnection": false,
    "_removedContLen": false,
    "_removedTE": false,
    "_contentLength": null,
    "_hasBody": true,
    "_trailer": "",
    "finished": false,
    "_headerSent": false,
    "socket": {
        "connecting": false,
        "_hadError": false,
        "_parent": null,
        "_host": null,
        "_readableState": {
            "objectMode": false,
            "highWaterMark": 16384,
            "buffer": {"head": null, "tail": null, "length": 0},
            "length": 0,
            "pipes": null,
            "pipesCount": 0,
            "flowing": true,
            "ended": false,
            "endEmitted": false,
            "reading": true,
            "sync": false,
            "needReadable": true,
            "emittedReadable": false,
            "readableListening": false,
            "resumeScheduled": false,
            "paused": false,
            "emitClose": false,
            "autoDestroy": false,
            "destroyed": false,
            "defaultEncoding": "utf8",
            "awaitDrain": 0,
            "readingMore": false,
            "decoder": null,
            "encoding": null
        },
        "readable": true,
        "_events": {"end": [null, null], "close": [null, null]},
        "_eventsCount": 8,
        "_writableState": {
            "objectMode": false,
            "highWaterMark": 16384,
            "finalCalled": false,
            "needDrain": false,
            "ending": false,
            "ended": false,
            "finished": false,
            "destroyed": false,
            "decodeStrings": false,
            "defaultEncoding": "utf8",
            "length": 0,
            "writing": false,
            "corked": 0,
            "sync": true,
            "bufferProcessing": false,
            "writecb": null,
            "writelen": 0,
            "bufferedRequest": null,
            "lastBufferedRequest": null,
            "pendingcb": 0,
            "prefinished": false,
            "errorEmitted": false,
            "emitClose": false,
            "autoDestroy": false,
            "bufferedRequestCount": 0,
            "corkedRequestsFree": {"next": null, "entry": null}
        },
        "writable": true,
        "allowHalfOpen": true,
        "_sockname": null,
        "_pendingData": null,
        "_pendingEncoding": "",
        "server": {
            "_events": {},
            "_eventsCount": 2,
            "_connections": 2,
            "_handle": {"reading": false},
            "_usingWorkers": false,
            "_workers": [],
            "_unref": false,
            "allowHalfOpen": true,
            "pauseOnConnect": false,
            "httpAllowHalfOpen": false,
            "timeout": 120000,
            "keepAliveTimeout": 5000,
            "maxHeadersCount": null,
            "headersTimeout": 40000,
            "_connectionKey": "6::::3000"
        },
        "_server": {
            "_events": {},
            "_eventsCount": 2,
            "_connections": 2,
            "_handle": {"reading": false},
            "_usingWorkers": false,
            "_workers": [],
            "_unref": false,
            "allowHalfOpen": true,
            "pauseOnConnect": false,
            "httpAllowHalfOpen": false,
            "timeout": 120000,
            "keepAliveTimeout": 5000,
            "maxHeadersCount": null,
            "headersTimeout": 40000,
            "_connectionKey": "6::::3000"
        },
        "timeout": 120000,
        "parser": {
            "_headers": [], "_url": "", "socket": "[Circular]", "incoming": {
                "_readableState": {
                    "objectMode": false,
                    "highWaterMark": 16384,
                    "buffer": {"head": null, "tail": null, "length": 0},
                    "length": 0,
                    "pipes": null,
                    "pipesCount": 0,
                    "flowing": true,
                    "ended": true,
                    "endEmitted": true,
                    "reading": false,
                    "sync": false,
                    "needReadable": false,
                    "emittedReadable": false,
                    "readableListening": false,
                    "resumeScheduled": false,
                    "paused": false,
                    "emitClose": true,
                    "autoDestroy": false,
                    "destroyed": false,
                    "defaultEncoding": "utf8",
                    "awaitDrain": 0,
                    "readingMore": false,
                    "decoder": null,
                    "encoding": null
                },
                "readable": false,
                "_events": {},
                "_eventsCount": 1,
                "socket": "[Circular]",
                "connection": "[Circular]",
                "httpVersionMajor": 1,
                "httpVersionMinor": 1,
                "httpVersion": "1.1",
                "complete": true,
                "headers": {
                    "content-type": "application/json",
                    "user-agent": "PostmanRuntime/7.22.0",
                    "accept": "*/*",
                    "cache-control": "no-cache",
                    "postman-token": "7a37a184-e9d8-45e2-9371-5499473afa29",
                    "host": "localhost:3000",
                    "accept-encoding": "gzip, deflate, br",
                    "content-length": "452",
                    "connection": "keep-alive"
                },
                "rawHeaders": ["Content-Type", "application/json", "User-Agent", "PostmanRuntime/7.22.0", "Accept", "*/*", "Cache-Control", "no-cache", "Postman-Token", "7a37a184-e9d8-45e2-9371-5499473afa29", "Host", "localhost:3000", "Accept-Encoding", "gzip, deflate, br", "Content-Length", "452", "Connection", "keep-alive"],
                "trailers": {},
                "rawTrailers": [],
                "aborted": false,
                "upgrade": false,
                "url": "/is/addpolygon",
                "method": "PUT",
                "statusCode": null,
                "statusMessage": null,
                "client": "[Circular]",
                "_consuming": true,
                "_dumped": false,
                "baseUrl": "",
                "originalUrl": "/is/addpolygon",
                "_parsedUrl": {
                    "protocol": null,
                    "slashes": null,
                    "auth": null,
                    "host": null,
                    "port": null,
                    "hostname": null,
                    "hash": null,
                    "search": null,
                    "query": null,
                    "pathname": "/is/addpolygon",
                    "path": "/is/addpolygon",
                    "href": "/is/addpolygon",
                    "_raw": "/is/addpolygon"
                },
                "params": {},
                "query": {},
                "res": {
                    "_events": {},
                    "_eventsCount": 1,
                    "outputData": [],
                    "outputSize": 0,
                    "writable": true,
                    "_last": false,
                    "chunkedEncoding": false,
                    "shouldKeepAlive": true,
                    "useChunkedEncodingByDefault": true,
                    "sendDate": true,
                    "_removedConnection": false,
                    "_removedContLen": false,
                    "_removedTE": false,
                    "_contentLength": null,
                    "_hasBody": true,
                    "_trailer": "",
                    "finished": false,
                    "_headerSent": false,
                    "socket": "[Circular]",
                    "connection": "[Circular]",
                    "_header": null,
                    "_sent100": false,
                    "_expect_continue": false,
                    "req": "[Circular]",
                    "locals": {}
                },
                "body": {
                    "type": "Feature",
                    "properties": {"name": "ret2"},
                    "geometry": {"type": "Polygon", "coordinates": [[[10, 10], [50, 10], [10, 50], [10, 10]]]}
                },
                "_body": true
            }, "outgoing": null, "maxHeaderPairs": 2000, "_consumed": true, "parsingHeadersStart": 1585952980481
        },
        "_paused": false,
        "_httpMessage": {
            "_events": {},
            "_eventsCount": 1,
            "outputData": [],
            "outputSize": 0,
            "writable": true,
            "_last": false,
            "chunkedEncoding": false,
            "shouldKeepAlive": true,
            "useChunkedEncodingByDefault": true,
            "sendDate": true,
            "_removedConnection": false,
            "_removedContLen": false,
            "_removedTE": false,
            "_contentLength": null,
            "_hasBody": true,
            "_trailer": "",
            "finished": false,
            "_headerSent": false,
            "socket": "[Circular]",
            "connection": "[Circular]",
            "_header": null,
            "_sent100": false,
            "_expect_continue": false,
            "req": "[Circular]",
            "locals": {}
        }
    },
    "connection": {
        "connecting": false,
        "_hadError": false,
        "_parent": null,
        "_host": null,
        "_readableState": {
            "objectMode": false,
            "highWaterMark": 16384,
            "buffer": {"head": null, "tail": null, "length": 0},
            "length": 0,
            "pipes": null,
            "pipesCount": 0,
            "flowing": true,
            "ended": false,
            "endEmitted": false,
            "reading": true,
            "sync": false,
            "needReadable": true,
            "emittedReadable": false,
            "readableListening": false,
            "resumeScheduled": false,
            "paused": false,
            "emitClose": false,
            "autoDestroy": false,
            "destroyed": false,
            "defaultEncoding": "utf8",
            "awaitDrain": 0,
            "readingMore": false,
            "decoder": null,
            "encoding": null
        },
        "readable": true,
        "_events": {"end": [null, null], "close": [null, null]},
        "_eventsCount": 8,
        "_writableState": {
            "objectMode": false,
            "highWaterMark": 16384,
            "finalCalled": false,
            "needDrain": false,
            "ending": false,
            "ended": false,
            "finished": false,
            "destroyed": false,
            "decodeStrings": false,
            "defaultEncoding": "utf8",
            "length": 0,
            "writing": false,
            "corked": 0,
            "sync": true,
            "bufferProcessing": false,
            "writecb": null,
            "writelen": 0,
            "bufferedRequest": null,
            "lastBufferedRequest": null,
            "pendingcb": 0,
            "prefinished": false,
            "errorEmitted": false,
            "emitClose": false,
            "autoDestroy": false,
            "bufferedRequestCount": 0,
            "corkedRequestsFree": {"next": null, "entry": null}
        },
        "writable": true,
        "allowHalfOpen": true,
        "_sockname": null,
        "_pendingData": null,
        "_pendingEncoding": "",
        "server": {
            "_events": {},
            "_eventsCount": 2,
            "_connections": 2,
            "_handle": {"reading": false},
            "_usingWorkers": false,
            "_workers": [],
            "_unref": false,
            "allowHalfOpen": true,
            "pauseOnConnect": false,
            "httpAllowHalfOpen": false,
            "timeout": 120000,
            "keepAliveTimeout": 5000,
            "maxHeadersCount": null,
            "headersTimeout": 40000,
            "_connectionKey": "6::::3000"
        },
        "_server": {
            "_events": {},
            "_eventsCount": 2,
            "_connections": 2,
            "_handle": {"reading": false},
            "_usingWorkers": false,
            "_workers": [],
            "_unref": false,
            "allowHalfOpen": true,
            "pauseOnConnect": false,
            "httpAllowHalfOpen": false,
            "timeout": 120000,
            "keepAliveTimeout": 5000,
            "maxHeadersCount": null,
            "headersTimeout": 40000,
            "_connectionKey": "6::::3000"
        },
        "timeout": 120000,
        "parser": {
            "_headers": [], "_url": "", "socket": "[Circular]", "incoming": {
                "_readableState": {
                    "objectMode": false,
                    "highWaterMark": 16384,
                    "buffer": {"head": null, "tail": null, "length": 0},
                    "length": 0,
                    "pipes": null,
                    "pipesCount": 0,
                    "flowing": true,
                    "ended": true,
                    "endEmitted": true,
                    "reading": false,
                    "sync": false,
                    "needReadable": false,
                    "emittedReadable": false,
                    "readableListening": false,
                    "resumeScheduled": false,
                    "paused": false,
                    "emitClose": true,
                    "autoDestroy": false,
                    "destroyed": false,
                    "defaultEncoding": "utf8",
                    "awaitDrain": 0,
                    "readingMore": false,
                    "decoder": null,
                    "encoding": null
                },
                "readable": false,
                "_events": {},
                "_eventsCount": 1,
                "socket": "[Circular]",
                "connection": "[Circular]",
                "httpVersionMajor": 1,
                "httpVersionMinor": 1,
                "httpVersion": "1.1",
                "complete": true,
                "headers": {
                    "content-type": "application/json",
                    "user-agent": "PostmanRuntime/7.22.0",
                    "accept": "*/*",
                    "cache-control": "no-cache",
                    "postman-token": "7a37a184-e9d8-45e2-9371-5499473afa29",
                    "host": "localhost:3000",
                    "accept-encoding": "gzip, deflate, br",
                    "content-length": "452",
                    "connection": "keep-alive"
                },
                "rawHeaders": ["Content-Type", "application/json", "User-Agent", "PostmanRuntime/7.22.0", "Accept", "*/*", "Cache-Control", "no-cache", "Postman-Token", "7a37a184-e9d8-45e2-9371-5499473afa29", "Host", "localhost:3000", "Accept-Encoding", "gzip, deflate, br", "Content-Length", "452", "Connection", "keep-alive"],
                "trailers": {},
                "rawTrailers": [],
                "aborted": false,
                "upgrade": false,
                "url": "/is/addpolygon",
                "method": "PUT",
                "statusCode": null,
                "statusMessage": null,
                "client": "[Circular]",
                "_consuming": true,
                "_dumped": false,
                "baseUrl": "",
                "originalUrl": "/is/addpolygon",
                "_parsedUrl": {
                    "protocol": null,
                    "slashes": null,
                    "auth": null,
                    "host": null,
                    "port": null,
                    "hostname": null,
                    "hash": null,
                    "search": null,
                    "query": null,
                    "pathname": "/is/addpolygon",
                    "path": "/is/addpolygon",
                    "href": "/is/addpolygon",
                    "_raw": "/is/addpolygon"
                },
                "params": {},
                "query": {},
                "res": {
                    "_events": {},
                    "_eventsCount": 1,
                    "outputData": [],
                    "outputSize": 0,
                    "writable": true,
                    "_last": false,
                    "chunkedEncoding": false,
                    "shouldKeepAlive": true,
                    "useChunkedEncodingByDefault": true,
                    "sendDate": true,
                    "_removedConnection": false,
                    "_removedContLen": false,
                    "_removedTE": false,
                    "_contentLength": null,
                    "_hasBody": true,
                    "_trailer": "",
                    "finished": false,
                    "_headerSent": false,
                    "socket": "[Circular]",
                    "connection": "[Circular]",
                    "_header": null,
                    "_sent100": false,
                    "_expect_continue": false,
                    "req": "[Circular]",
                    "locals": {}
                },
                "body": {
                    "type": "Feature",
                    "properties": {"name": "ret2"},
                    "geometry": {"type": "Polygon", "coordinates": [[[10, 10], [50, 10], [10, 50], [10, 10]]]}
                },
                "_body": true
            }, "outgoing": null, "maxHeaderPairs": 2000, "_consumed": true, "parsingHeadersStart": 1585952980481
        },
        "_paused": false,
        "_httpMessage": {
            "_events": {},
            "_eventsCount": 1,
            "outputData": [],
            "outputSize": 0,
            "writable": true,
            "_last": false,
            "chunkedEncoding": false,
            "shouldKeepAlive": true,
            "useChunkedEncodingByDefault": true,
            "sendDate": true,
            "_removedConnection": false,
            "_removedContLen": false,
            "_removedTE": false,
            "_contentLength": null,
            "_hasBody": true,
            "_trailer": "",
            "finished": false,
            "_headerSent": false,
            "socket": "[Circular]",
            "connection": "[Circular]",
            "_header": null,
            "_sent100": false,
            "_expect_continue": false,
            "req": "[Circular]",
            "locals": {}
        }
    },
    "_header": null,
    "_sent100": false,
    "_expect_continue": false,
    "req": {
        "_readableState": {
            "objectMode": false,
            "highWaterMark": 16384,
            "buffer": {"head": null, "tail": null, "length": 0},
            "length": 0,
            "pipes": null,
            "pipesCount": 0,
            "flowing": true,
            "ended": true,
            "endEmitted": true,
            "reading": false,
            "sync": false,
            "needReadable": false,
            "emittedReadable": false,
            "readableListening": false,
            "resumeScheduled": false,
            "paused": false,
            "emitClose": true,
            "autoDestroy": false,
            "destroyed": false,
            "defaultEncoding": "utf8",
            "awaitDrain": 0,
            "readingMore": false,
            "decoder": null,
            "encoding": null
        },
        "readable": false,
        "_events": {},
        "_eventsCount": 1,
        "socket": "[Circular]",
        "connection": "[Circular]",
        "httpVersionMajor": 1,
        "httpVersionMinor": 1,
        "httpVersion": "1.1",
        "complete": true,
        "headers": {
            "content-type": "application/json",
            "user-agent": "PostmanRuntime/7.22.0",
            "accept": "*/*",
            "cache-control": "no-cache",
            "postman-token": "7a37a184-e9d8-45e2-9371-5499473afa29",
            "host": "localhost:3000",
            "accept-encoding": "gzip, deflate, br",
            "content-length": "452",
            "connection": "keep-alive"
        },
        "rawHeaders": ["Content-Type", "application/json", "User-Agent", "PostmanRuntime/7.22.0", "Accept", "*/*", "Cache-Control", "no-cache", "Postman-Token", "7a37a184-e9d8-45e2-9371-5499473afa29", "Host", "localhost:3000", "Accept-Encoding", "gzip, deflate, br", "Content-Length", "452", "Connection", "keep-alive"],
        "trailers": {},
        "rawTrailers": [],
        "aborted": false,
        "upgrade": false,
        "url": "/is/addpolygon",
        "method": "PUT",
        "statusCode": null,
        "statusMessage": null,
        "client": "[Circular]",
        "_consuming": true,
        "_dumped": false,
        "baseUrl": "",
        "originalUrl": "/is/addpolygon",
        "_parsedUrl": {
            "protocol": null,
            "slashes": null,
            "auth": null,
            "host": null,
            "port": null,
            "hostname": null,
            "hash": null,
            "search": null,
            "query": null,
            "pathname": "/is/addpolygon",
            "path": "/is/addpolygon",
            "href": "/is/addpolygon",
            "_raw": "/is/addpolygon"
        },
        "params": {},
        "query": {},
        "res": {
            "_events": {},
            "_eventsCount": 1,
            "outputData": [],
            "outputSize": 0,
            "writable": true,
            "_last": false,
            "chunkedEncoding": false,
            "shouldKeepAlive": true,
            "useChunkedEncodingByDefault": true,
            "sendDate": true,
            "_removedConnection": false,
            "_removedContLen": false,
            "_removedTE": false,
            "_contentLength": null,
            "_hasBody": true,
            "_trailer": "",
            "finished": false,
            "_headerSent": false,
            "socket": "[Circular]",
            "connection": "[Circular]",
            "_header": null,
            "_sent100": false,
            "_expect_continue": false,
            "req": "[Circular]",
            "locals": {}
        },
        "body": {
            "type": "Feature",
            "properties": {"name": "ret2"},
            "geometry": {"type": "Polygon", "coordinates": [[[10, 10], [50, 10], [10, 50], [10, 10]]]}
        },
        "_body": true
    },
    "locals": {},
    "level": "info",
    "message": "<<<<<<<<<<",
    "timestamp": "2020-04-04 02:59:40"
};
